[package]
name = "litt_index"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tantivy = "0.19.2"
mockall_double = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
