[workspace]

members = [
    "litt",
    "search",
    "index",
    "shared"
]

[workspace.dependencies]
tantivy = "0.19.2"
mockall_double = "0.3.0"
mockall = "0.11.4"
lopdf = "0.29.0"
args = "2.2.0"
getopts = "0.2"
