[workspace]

members = [
    "litt",
    "search",
    "index",
    "shared"
]

[workspace.dependencies]
tantivy = "0.21.0"
clap = "4.2.2"
serde = "1.0.160"
serde_json = "1.0"
shellexpand = "3.1.0"
uuid = "1.3.2"
colored = "2"
