[package]
name = "litt_search"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
tantivy = { workspace = true }
litt_shared = { path = "../shared" }
litt_index = { path = "../index" }
tokio = { workspace = true }

