use clap::Parser;
mod cli;

fn main() {
    let args = cli::Cli::parse();

    // TODO (fux): in case of missing index name, all indices should be listed.
    // Find a way to do that since clap automatically generates a (pretty good)
    // error msg. Ideally we can add the list of availible indexes to the error
    // generated by clap.

    if !args.init.is_empty() {
        println!(
            "Creating new index \"{}\" at: {}.",
            args.litt_index, args.init
        );
    } else if args.update {
        println!("Updating index \"{}\".", args.litt_index);
    } else if !args.term.is_empty() {
        println!("Search index \"{}\" for {}", args.litt_index, args.term);
    } else {
        println!("Starting interactive search for \"{}\".", args.litt_index);
    }
}
